# run cargo install mdbook mdbook-toc mdbook-linkcheck2

[book]
authors = ["Cliff Brake"]
language = "en"
src = "."
title = "Simple IoT"

#[preprocessor.toc]

[output.html]
git-repository-url = "https://github.com/simpleiot/simpleiot"
edit-url-template = "https://github.com/simpleiot/simpleiot/edit/master/{path}"

# [output.linkcheck2]
# follow-web-links = true
# exclude = [
#   'localhost*',
#   '192*',
#   'modbus*',
#   'shelly*'
# ]
