name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go 1.24
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.10
        id: go

      - name: Set up nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
        id: node

      - name: Get dependencies
        run: |
          . envsetup.sh
          siot_install_frontend_deps

      - name: Test/lint frontend
        run: |
          . envsetup.sh
          siot_build_frontend
          siot_test_frontend

      - name: Test Backend
        run: |
          node --version
          . envsetup.sh
          go test -p=1 -race "$@" ./...

      - name: Lint backend
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=5m
